language: node_js
matrix:
  include:
#  - node_js: 6
#  - node_js: 8
  - node_js: 10
#  - node_js: 11

addons:
  firefox: "68.0.1"

#before_install:
#  - npm install -g bower
#  - bower install
#sudo: required

install:
  - "export DISPLAY=:99.0"
  - "xvfb-run --auto-servernum --server-args='-screen 0 640x480x24'"
#  - "sh -e /etc/init.d/xvfb start"
#  - bower install kin-base

script:
# - npm run test
  - npm run version


after_success:
#  - npm publish --access public
#- |
#  # Send report to coveralls but only once
#  if [ -z "${SAUCE}" ] && [ "${TRAVIS_NODE_VERSION}" = "10" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
#    gulp submit-coverage
#  fi


#branches:
#  only:
#    - master


notifications:
  email: false



deploy:
#- provider: npm
#  email: udi.altaratz@kon.org
#  api_key: $API_TOKEN
#  on:
#    tags: true
#    repo: kinecosystem/js-kin-base
#    node: 10
#- provider: script
#  script: "./bower_publish.sh"
#  skip_cleanup: true
#  on:
#    tags: true
#    repo: kinecosystem/js-kin-base
#    node: 10
