language: node_js
matrix:
  include:
  - node_js: 6
  - node_js: 8
  - node_js: 10
  - node_js: 11

before_install:
  - npm install -g bower
  - bower install
sudo: required

#install:
#  - bower install kin-base

script:
- |
  if [ "${SAUCE}" = "true" ]; then
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      gulp test:sauce
    else
      echo "Pull request - skip Sauce Labs testing..."
    fi
  else
    # Ugly but it's the only way to make istanbul generate coverage report
    babel-node ./node_modules/gulp/bin/gulp.js test:node
  fi


after_success:
- |
  # Send report to coveralls but only once
  if [ -z "${SAUCE}" ] && [ "${TRAVIS_NODE_VERSION}" = "10" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    gulp submit-coverage
  fi

#branches:
#  only:
#    - master


notifications:
  email: false



deploy:
- provider: npm
  email: udi.altaratz@kon.org
  api_key: $API_TOKEN
  on:
    tags: true
    repo: kinecosystem/js-kin-base
    node: 10
- provider: script
  script: "./bower_publish.sh"
  skip_cleanup: true
  on:
    tags: true
    repo: kinecosystem/js-kin-base
    node: 10
